local defaults = require("wvim.config.defaults")
local settings = require("wvim.config.settings")
settings.load_settings()
local bootstrap = require("wvim.bootstrap")
vim.cmd([[colorscheme catppuccin]])
